[package]
name = "hyper-trust-dns"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
edition = "2018"

[dependencies]
hyper = "0.12"
trust-dns-resolver = { version = "0.11.1", default-features = false, features = ["tokio", "dnssec-ring"] }
