[package]
name = "hyper-trust-dns"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
edition = "2018"

[dependencies]
hyper = "*"
trust-dns-resolver = { git = "https://github.com/bluejekyll/trust-dns", default-features = false, features = ["tokio", "dnssec-ring"] }